//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemCredit.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public string NumCpt { get; set; }
        public string CodeCredit { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<int> Duree { get; set; }
        public string EtatDossier { get; set; }
    }
}
