//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManager.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicalEntities : DbContext
    {
        public medicalEntities()
            : base("name=medicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comtab> Comtab { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Rendez> Rendez { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
