//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManager.Data.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Comtab = new HashSet<Comtab>();
            this.Rendez = new HashSet<Rendez>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Nom { get; set; }
        [Required]
        public string Prenom { get; set; }
        [Required]
        public System.DateTime Date_cre { get; set; }
        public Nullable<decimal> CIN { get; set; }
        [Required]
        public string Sexe { get; set; }
        public Nullable<decimal> Telephone { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Matricule_CNAM { get; set; }
        public Nullable<System.DateTime> Date_nais { get; set; }
        [Required]
        public string Nom_fiche { get; set; }
        public string Profession { get; set; }
    
        public virtual ICollection<Comtab> Comtab { get; set; }
        public virtual ICollection<Rendez> Rendez { get; set; }
    }
}
