//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManager.Data.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Rendez
    {
        public int Id { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        [Required]
        public int Patient_Id { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
